### ISSUE TITLE
Suggestion use HTML list functions

### ISSUE THREAD

**Issue by jkone27** [AngelMunoz/Hox#1]
Just wonder why extension / fluent methods (or could be ok for C# compat) but in F# I think Feliz approach works better , with list functions as it allows to use list comorehensions to build html nicely and in a dynamic way ! With for loops inside list CEs

**Comment by AngelMunoz** [comment]
Hey there, thanks for asking!

Please keep in mind that the DSL is the least important thing from this repository, the important bits are:

- Async rendering
- Async Chunk Rendering
- Natural side by side asynchronouse elements (e.g. `Task<Node>` or `Async<Node>` next to `Node` or as a children/parent of sync/async Nodes)

The building blocks are there and anyone can build a particular DSL flavor on top of the core types `Node`, `Element` and `Attribute`, you may even use [Feliz.Engine](https://github.com/alfonsogarciacaro/Feliz.Engine) with those basic blocks to have a Feliz based DSL, you may lose the third bullet as I'm not sure Feliz.Engine would allow the usage of async nodes.

That being said, let's talk about the DSL:

The main idea is to have a compact and simple to use DSL, also second node the DSL is still in an experimentation phase, the final design is not yet there.

Using List based DSLs tends to increment indentation heavily on larger trees which has very little appealing for me and even others I've talked with, specially from outside the F# community; These DSLs look very alien and far from what one would say "this is html".

You can still use list comprehensions when you use `fragment []`, so you're not losing them at all, they've just been moved more to a place of "I need this" rather than "I'll use this just because I can".

These fluent methods are just a functional version of the pipes to reduce nesting where possible.

As an example:

```fsharp
open type Html
article [
    prop.className "thing"
    prop.style "display:inline"
    prop.children [
        section [
            prop.id "my-id"
            prop.children [
                text "Hello there!"
            ]
        ]
    ]
]
```

Surely you can use 2 spaces or even different formatting options, but the indentation is inevitable, plus the list brackets start adding noise slowly, it is kind of worse for two list based DSLs.

In contrast I'm looking for a simpler way to define that
```fsharp
open type Htmelo.Dsl.H

el(
    "article.thing[style=display:inline;]",
    el("section#my-id", text "Hello there!")
)
```

Since folks writing html are likely to be familiar with `CSS` selectors I figured out it would be a great way to reduce that kind of boilerplate.

At this point in time, I've updated the `el` function to have a `Node params array`, so you don't actually have to nest or call `children` on the node! they will be able to go side-by-side with the element declaration.

The "worst case scenario" for this DSL is an element which has a ton of ids, attributes and classes, you would end up with something like this

```fsharp
el("div#super-div.is-one.is-two.is-three.super-long-class-which-occupies-space.we-re-not-even-started[hx-get=/my/api/endpoint][hx-target=#the-super-long-id-of-another-element].yet-another-class.because-why-not", ...children)
```

The parser has been extended to allow spaces or line breaks to avoid this, the attr extension method will simply allow other stuff like async attributes

```fsharp
el(@"div#super-div.is-one.is-two.is-three
    .super-long-class-which-occupies-space
    .we-re-not-even-started
    [hx-get=/my/api/endpoint]
    [hx-target=#the-super-long-id-of-another-element]
    .yet-another-class.because-why-not",
   ...children)
   .attr("data-csv-row", task { 
     let! row = myService.getRow(id)
     return String.Join(',', row)
   })
```
So ideally this is compact, descriptive and close enough to what webdevs outside F# land would like.

I don't expect many of the F# folks to follow that as they're often looking for type safety and that's not a goal here just yet, maybe in the future with an F# analyzer like [Npgsql.FSharp.Analyzer](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer) that goal can be attained.


So in general that's why. It is very funny to experiment with the DSL, but the real gain/goal is to have async/rendering and have side-by-side node/async nodes, Which I'd only hope we could make them available in other libraries in the community as it opens really cool stuff that may be compatible with solutions in the JS ecosystem

**Comment by AngelMunoz** [comment]
@jkone27 As a PoC of the previously thing said, I added a sample with Feliz.Engine here:
https://github.com/AngelMunoz/Htmelo/blob/main/samples/FelizEngine/Program.fs

In general it plays almost "out of the box", but with a few type extensions it works nicely and forget what I said about losing async components, they also work there! (the benefits of almost everything being a node)
Attributes from the engine don't play too well with my async core because attributes are part of `Element` rather than `Node` but maybe with a few helpers it can be used nicely.

**Comment by AngelMunoz** [comment]
Given that it is very very low maintenance thanks to Feliz.Engine, I'll keep it as an official alternate DSL as well, the code resides here: https://github.com/AngelMunoz/Hox/tree/main/src/Hox.Feliz
